name: 'Zenodo Publish'
description: 'Publishes a new version of the provided Zenodo Deposition'
inputs:
  zenodo_deposition_id:
    description: 'The ID of the Zenodo Deposition to publish to.'
    required: true
  zenodo_metadata:
    description: 'The Json file containing metadata for your deposition'
    required: false
    default: '.zenodo.json'
  whitelist_uploads:
    description: 'The file with a filename per line that should be uploaded to the deposition'
    required: false
    default: '.whitelist_upload'
  zenodo_server:
    description: 'The URL of the Zenodo Server to use, set "https://zenodo.org" for production'
    required: false
    default: 'https://sandbox.zenodo.org'
secrets:
  zenodo_token:
    description: 'The Auth Token for Zenodo'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install zenodo-rest
      shell: bash
      env:
        ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
        ZENODO_URL: ${{ input.zenodo_server }}
      run: |
        python -m pip install --upgrade pip
        pip install zenodo-rest=0.0.0b2
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch Latest Deposition
      shell: bash
      env:
        ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
        ZENODO_URL: ${{ input.zenodo_server }}
      run: |
        zenodo-rest depositions retrieve ${{ input.zenodo_deposition_id }} --dest tmp/.zenodo_deposition.json
    - name: Update metadata
      shell: bash
      env:
        ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
        ZENODO_URL: ${{ input.zenodo_server }}
      run: |
        zenodo-rest depositions update tmp/.zenodo_deposition.json ${{ input.zenodo_metadata }}
    - if: [ -f .whitelist_upload ]
      name: Upload attachments 
      shell: bash
      env:
        ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
        ZENODO_URL: ${{ input.zenodo_server }}
      run: |
        LATEST_DOI=$(zenodo-rest depositions doi latest tmp/.zenodo_deposition.json)
        LATEST_DRAFT_DOI=$(zenodo-rest depositions doi latest-draft .zenodo_deposition.json)
        xargs -a .whitelist_upload -I {} zenodo-rest depositions upload-file tmp/.zenodo_deposition.json {}
    - name: Publish updated deposition
      shell: bash
      env:
        ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
        ZENODO_URL: ${{ input.zenodo_server }}
      run: zenodo-rest depositions publish tmp/.zenodo_deposition.json
    - if: test -f tmp/.zenodo_deposition.json
      name: Cleanup 
      shell: bash
      run: rm tmp/.zenodo_deposition.json
