name: 'Zenodo New Version'
description: 'Creates a new version of the provided Zenodo Deposition'
inputs:
  zenodo_deposition_id:
    description: 'The ID of the Zenodo Deposition to create a new version of.'
    required: true
  whitelist_replace_doi:
    description: 'The file with a filename per line in which the doi should be replaced'
    required: false
    default: '.whitelist_upload'
  zenodo_server:
    description: 'The URL of the Zenodo Server to use, set "https://zenodo.org" for production'
    required: false
    default: 'https://sandbox.zenodo.org'
  zenodo_token:
    description: 'The Auth Token for Zenodo'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install zenodo-rest
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install zenodo-rest==0.0.0b4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch Latest Deposition
      shell: bash
      env:
        ZENODO_TOKEN: ${{ inputs.zenodo_token }}
        ZENODO_URL: ${{ inputs.zenodo_server }}
      run: |
        mkdir tmp
        echo $TMP_DEPOSITION_JSON
        zenodo-rest depositions retrieve ${{ inputs.zenodo_deposition_id }} --dest .tmp_zenodo_deposition.json
    - name: Create new version 
      shell: bash
      env:
        ZENODO_TOKEN: ${{ inputs.zenodo_token }}
        ZENODO_URL: ${{ inputs.zenodo_server }}
      run: |
        # Create new version
        cat .tmp_zenodo_deposition.json
        zenodo-rest depositions new-version .tmp_zenodo_deposition.json --dest .tmp_zenodo_deposition.json
    - name: Replace DOIs
      shell: bash
      env:
        ZENODO_TOKEN: ${{ inputs.zenodo_token }}
        ZENODO_URL: ${{ inputs.zenodo_server }}
      run: |
        if test ! -f .whitelist_replace_doi; then exit; fi
        # Replace DOI in whiteliste files
        LATEST_DOI=$(zenodo-rest depositions doi latest .tmp_zenodo_deposition.json)
        LATEST_DRAFT_DOI=$(zenodo-rest depositions doi latest-draft .tmp_zenodo_deposition.json)
        xargs -a .whitelist_replace_doi -I {} sed -i -e "s/$LATEST_DOI/$LATEST_DRAFT_DOI/g" {}
    - name: Cleanup 
      shell: bash
      run: |
        if test ! -f .tmp_zenodo_deposition.json
        then
          echo "Nothing to cleanup, exiting early"
          exit
         fi
        rm .tmp_zenodo_deposition.json
