name: Basic Workflow

on:
  push:
    branches: [ main ]
    paths:
      - '**.txt'
      - '**.md'
      - '**.csv'
  workflow_dispatch:

jobs:
  new_version:
    name: Create new version of zenodo deposition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./new-version/action.yml
        with:
          zenodo_deposition: 1054411
          zenodo_token: ${{ secrets.ZENODO_SANDBOX_TOKEN }}
      - uses: ./publish/action.yml
        with:
          zenodo_deposition: 1054411
          zenodo_token: ${{ secrets.ZENODO_SANDBOX_TOKEN }}
